Repository ResQSync/ResQSyncWeb, pull requests merged in 2023-10, with the labels that each got.

#4 added links to github and discord in footer
  src/components/Footer.tsx
Labels: hacktoberfest-accepted

#9 Privacy policy page
  src/app/privacy/page.tsx
Labels: enhancement, hacktoberfest-accepted, UI

#11 nav bar changes
  src/components/NavBar.tsx
Labels: good first issue, hacktoberfest-accepted

#12 changes in footer for privacy policy page linking
  src/components/Footer.tsx
Labels: hacktoberfest-accepted

#13 FAQs Added for ResQSync APP
  FAQs.md
Labels: documentation, hacktoberfest-accepted

#14 faq page creation and linking it to nav bar
  FAQs.md
  src/app/faq/page.tsx
  src/components/NavBar.tsx
Labels: enhancement, hacktoberfest-accepted, UI
